version: "3.9"
services:
  server:
    image: server-image
    build: ./service-a-node
    ports:
      - "7001:7001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  fastapi:
    image: fastapi-image
    build: ./service-b-fastapi
    ports:
      - "7002:7002"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: frontend-image
    build: ./frontend
    ports:
      - "8088:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
